#!/bin/bash

# Get the C file name from the environment variable CFILE
CFILE=$CFILE

# Extract the name of the C file without the extension
CFILENAME=$(basename -- "$CFILE")
CFILENAME="${CFILENAME%.*}"

# Set the output file name to be the C file name with .s extension
OUTPUTFILE="$CFILENAME.s"

# Generate the assembly code and save it to the output file
gcc -S $CFILE -o $OUTPUTFILE
